name = "ubuntu"
tag = "noble"
aliases = ["24.04", "lts", "latest"]
description = "Ubuntu 24.04 LTS (Noble Numbat) server cloud image"
login = "cloud-init"

[[image]]
arch = "amd64"
format = "qcow2"
url = "https://cloud-images.ubuntu.com/releases/noble/release-20260911/ubuntu-24.04-server-cloudimg-amd64.img"
digest = "sha256:612b2c0cc1bc413a6cb8c38fd611794caf0f2b436c50013d8b3794db12ad7354"
size = 625256960
