name = "rocky"
tag = "10"
description = "Rocky Linux 10 generic cloud image"
login = "cloud-init"

[[image]]
arch = "amd64"
format = "qcow2"
url = "https://dl.rockylinux.org/pub/rocky/10/images/x86_64/Rocky-10-GenericCloud-Base-10.2-20260525.0.x86_64.qcow2"
digest = "sha256:9fc9e9ff16888bb68ac39b0392e25c9c92684d50c85f1cce6ab549363bbc4b48"
size = 544997376
