name = "rocky"
tag = "9"
aliases = ["latest"]
description = "Rocky Linux 9 generic cloud image"
login = "cloud-init"

[[image]]
arch = "amd64"
format = "qcow2"
url = "https://dl.rockylinux.org/pub/rocky/9/images/x86_64/Rocky-9-GenericCloud-Base-9.8-20260525.0.x86_64.qcow2"
digest = "sha256:92c206cc6f790c61583247eefe87890f8828420662c17cacf247cec78ab4eec8"
size = 645988352
