//! The per-instance key pair.
//!
//! Each instance gets its own key rather than borrowing the user's. It is
//! generated by `ssh-keygen`, which is already a mandatory dependency because
//! `vm ssh` shells out to `ssh`: writing an OpenSSH private key by hand would
//! mean implementing ed25519 to save a dependency that is already there.

use crate::error::{Error, Result};
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

/// Generates a key pair at `private`, returning the public key.
///
/// The key has no passphrase: it exists so that a machine this tool created
/// can be reached by the person who created it, and a prompt on every `vm ssh`
/// would only be answered by an agent holding the passphrase anyway.
pub fn generate(private: &Path, comment: &str) -> Result<String> {
    let output = Command::new("ssh-keygen")
        .arg("-t")
        .arg("ed25519")
        .arg("-N")
        .arg("")
        .arg("-q")
        .arg("-C")
        .arg(comment)
        .arg("-f")
        .arg(private)
        .output()
        .map_err(|source| {
            if source.kind() == std::io::ErrorKind::NotFound {
                missing()
            } else {
                Error::Launch {
                    program: "ssh-keygen".to_owned(),
                    source,
                }
            }
        })?;
    if !output.status.success() {
        return Err(Error::KeyGeneration {
            path: private.to_owned(),
            reason: String::from_utf8_lossy(&output.stderr).trim().to_owned(),
        });
    }
    read_public(private)
}

/// Reads the public half beside a private key.
pub fn read_public(private: &Path) -> Result<String> {
    let path = public_path(private);
    fs::read_to_string(&path)
        .map(|text| text.trim().to_owned())
        .map_err(|source| Error::State {
            path,
            action: "read the instance key",
            source,
        })
}

pub fn public_path(private: &Path) -> PathBuf {
    let mut path = private.as_os_str().to_owned();
    path.push(".pub");
    PathBuf::from(path)
}

const fn missing() -> Error {
    Error::MissingTool {
        binary: "ssh-keygen",
        package: "openssh-client",
        operation: "creating a key for a virtual machine",
    }
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used)]

    use super::*;

    struct Scratch(PathBuf);

    impl Scratch {
        fn new(label: &str) -> Self {
            let mut path = std::env::temp_dir();
            path.push(format!("vm-keys-{label}-{}", std::process::id()));
            let _ = fs::remove_dir_all(&path);
            fs::create_dir_all(&path).unwrap();
            Self(path)
        }

        fn key(&self) -> PathBuf {
            self.0.join("id_ed25519")
        }
    }

    impl Drop for Scratch {
        fn drop(&mut self) {
            let _ = fs::remove_dir_all(&self.0);
        }
    }

    #[test]
    fn a_generated_key_is_an_ed25519_pair() {
        let scratch = Scratch::new("pair");
        let public = generate(&scratch.key(), "vm-test").unwrap();
        assert!(public.starts_with("ssh-ed25519 "), "{public}");
        assert!(public.ends_with("vm-test"), "{public}");
        assert!(scratch.key().is_file());
        assert!(public_path(&scratch.key()).is_file());
    }

    /// The seed refuses anything that is not a public key, so what is
    /// generated here has to satisfy what is written there.
    #[test]
    fn a_generated_key_is_one_the_seed_will_accept() {
        let scratch = Scratch::new("seedable");
        let public = generate(&scratch.key(), "vm-test").unwrap();
        let seed = crate::seed::Seed {
            instance_id: "one".to_owned(),
            hostname: "one".to_owned(),
            user: "vm".to_owned(),
            authorized_key: public,
            mounts: Vec::new(),
        };
        assert!(seed.image().is_ok());
    }

    #[test]
    fn the_private_key_is_readable_only_by_its_owner() {
        use std::os::unix::fs::PermissionsExt as _;
        let scratch = Scratch::new("mode");
        generate(&scratch.key(), "vm-test").unwrap();
        let mode = fs::metadata(scratch.key()).unwrap().permissions().mode();
        assert_eq!(mode & 0o077, 0, "mode was {mode:o}");
    }

    #[test]
    fn each_key_is_its_own() {
        let first = Scratch::new("first");
        let second = Scratch::new("second");
        assert_ne!(
            generate(&first.key(), "vm").unwrap(),
            generate(&second.key(), "vm").unwrap()
        );
    }

    #[test]
    fn generating_over_a_key_that_is_already_there_is_refused() {
        let scratch = Scratch::new("existing");
        generate(&scratch.key(), "vm-test").unwrap();
        let error = generate(&scratch.key(), "vm-test").unwrap_err();
        assert_eq!(error.kind(), "key-generation-failed");
    }

    #[test]
    fn a_key_that_cannot_be_written_is_reported() {
        let error = generate(Path::new("/nonexistent/directory/id_ed25519"), "vm").unwrap_err();
        assert_eq!(error.kind(), "key-generation-failed");
    }

    #[test]
    fn the_public_path_sits_beside_the_private_one() {
        assert_eq!(
            public_path(Path::new("/a/b/id_ed25519")),
            PathBuf::from("/a/b/id_ed25519.pub")
        );
    }

    #[test]
    fn reading_a_public_key_that_is_not_there_is_reported() {
        let scratch = Scratch::new("absent");
        assert_eq!(
            read_public(&scratch.key()).unwrap_err().kind(),
            "state-unusable"
        );
    }
}
