name = "fedora"
tag = "42"
description = "Fedora 42 Cloud Base"
login = "cloud-init"

[[image]]
arch = "amd64"
format = "qcow2"
url = "https://download.fedoraproject.org/pub/fedora/linux/releases/42/Cloud/x86_64/images/Fedora-Cloud-Base-Generic-42-1.1.x86_64.qcow2"
digest = "sha256:e401a4db2e5e04d1967b6729774faa96da629bcf3ba90b67d8d9cce9906bec0f"
size = 532217856
